### ISSUE TITLE
Add CategoryWatch Wiki Extension

### ISSUE THREAD

**Issue by lectrician1** [openstreetmap/operations#497] opened 2021-01-10 20:00 UTC
_[Initial Talk:Wiki Topic](https://wiki.openstreetmap.org/wiki/Talk:Wiki#Add_CategoryWatch_Extension)_

"The [CategoryWatch](https://www.mediawiki.org/wiki/Extension:CategoryWatch) extension extends watchlist functionality to include notification about membership changes of watched categories."

This would be extremely helpful to users:

- Who want to be notified when a Proposal is added to one of the [Proposals_by_status Categories](https://wiki.openstreetmap.org/wiki/Category:Proposals_by_status). A major convenience would be for users that don't want to subscribe to the Tagging Mailing list but still want to be notified when proposals become open to voting.
- Who monitor a Place Wikiproject's categories

**Comment by Tigerfell** [comment] 2021-01-11 13:47
Is this a duplicate of #351?

**Comment by lectrician1** [comment] 2021-01-11 14:29
I think so.
Especially after seeing [this discussion topic](https://www.mediawiki.org/wiki/Extension_talk:CategoryWatch/Archive#CategoryWatch_vs._$wgRCWatchCategoryMembership) on the Extension's Talk page, they must be similar.

However, it seems that the CategoryWatch extension automatically enables notifications whereas the Wiki variable requires users to enable them on their own.
If I was a new user I would like to probably have this enabled automatically as one would expect that the adding a Category to a watchlist would give membership change notifications just like how pages get page notifications. 
Not everyone will know about the setting on the Watchlist page.

**Comment by pnorman** [comment] 2021-02-24 21:41
Duplicate of #351

**Closed by pnorman** 2021-02-24 21:41 UTC
Labels: service:wiki
