### ISSUE TITLE
stats unavailable via https

### ISSUE THREAD

**Issue by Komzpa** [openstreetmap/operations#133] opened 2016-12-16 13:13 UTC
Opens fine:
http://stats.openstreetmap.org/cgi-bin/awstats.pl?config=www.openstreetmap.org

Opens into Chef control panel:
https://stats.openstreetmap.org/cgi-bin/awstats.pl?config=www.openstreetmap.org

**Comment by slachiewicz** [comment] 2017-02-13 14:59
After Let's Encrypt cert implementation:

_None of the common names in the certificate match the name that was entered (stats.openstreetmap.org). You may receive an error when accessing this site in a web browser._

Common name: acme.openstreetmap.org
SANs: acme.openstreetmap.org, acme.osm.org
Valid from February 11, 2017 to May 12, 2017

**Comment by tomhughes** [comment] 2017-02-13 15:03
Sorry, where did we say he had implemented letsencrypt for that domain? We didn't.

There was a tweet saying we had *started* rolling it out but there's still a long way to do to get everything switched over, and priority was for services already secured by a certificate that expires in a few weeks.

**Comment by slachiewicz** [comment] 2017-02-13 15:29
I think, commit https://github.com/openstreetmap/chef/commit/2e3b8963812e8727720c26429f716df736aec1c2 has been set default certificate on port 443 to acme.openstreetmap.org. Before there was default page for Chef control panel serverd from another virtual host :)

**Comment by tomhughes** [comment] 2017-02-13 15:32
The point is that we have never claimed to support https for that domain so anybody choosing to randomly change protocol from http to https gets to pick up the pieces themselves.

Yes, changes to other domains hosted on the same machine may result in a change in behaviour, because there is not defined or expected behaviour for https://stats.openstreetmap.org/ because that is not a URL we have ever published or invited anybody to use!

**Comment by tomhughes** [comment] 2017-02-13 15:53
Fixed in https://github.com/openstreetmap/chef/commit/fa6ed4fa1659e66d6e432fc8352089a2ae62ad6d.

**Closed by tomhughes** 2017-02-13 15:53 UTC
