### ISSUE TITLE
email send to sotm@openstreetmap.org are getting mangled into sotm@osmfoundation.org and not delivered

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#731] opened 2022-08-18 06:00 UTC
I send email to `sotm@openstreetmap.org`

```
To: sotm@openstreetmap.org
Subject: Please, consider affordability in selecting SOTM location and  codify it
Date: Thu, 18 Aug 2022 06:31:04 +0200
X-Mailer: Claws Mail 3.17.5 (GTK+ 2.24.32; x86_64-pc-linux-gnu)
```

I give email delivery error with

```
Your message wasn't delivered to sotm@osmfoundation.org because the address couldn't be found, or is unable to receive mail.
```

I am pretty sure that mangling is not happening on my computer.

**Comment by pnorman** [comment] 2022-08-18 06:01
Duplicate of #732. The issue is likely not mangling, but a missing alias on the osmfoundation email setup.

**Closed by pnorman** 2022-08-18 06:01 UTC
