### ISSUE TITLE
OSM Minutely Changeset Replication file: 006/136/122.osm.gz returns "The specified key does not exist."

### ISSUE THREAD

**Issue by pa5cal** [openstreetmap/operations#1142] opened 2024-08-14 05:36 UTC
The download of the following OSM changeset replication file

https://planet.openstreetmap.org/replication/changesets/006/136/122.osm.gz

is returning a

````
<Error>
   <Code>NoSuchKey</Code>
   <Message>The specified key does not exist.</Message>
   <Key>changesets/replication/minute/006/136/122.osm.gz</Key>
   <RequestId>TFVMHTP5SMFZEEDC</RequestId>
   <HostId>Ufi9ff2xpVBJb/uSa4ZM9pHt2YPZYBa/J/zGwU+xktf7mVLcVgZWYmYWGOlTFcWU/QpNPqkiBiU=</HostId>
</Error>
````

**Comment by tomhughes** [comment] 2024-08-14 07:55
This should be fixed now.

**Closed by tomhughes** 2024-08-14 07:55 UTC

**Comment by pa5cal** [comment] 2024-08-14 08:16
Now there is some issue with the following state file:
https://planet.openstreetmap.org/replication/changesets/006/136/468.state.txt

It's returning
`````
<Error>
   <Code>NoSuchKey</Code>
   <Message>The specified key does not exist.</Message>
   <Key>changesets/replication/minute/006/136/468.state.txt</Key>
   <RequestId>KFZW1HA3CDJ169X3</RequestId>
   <HostId>5Je4LlBJkSHe7dOFS66k+v98k1//ia271HGY6eiNYwRVig4DtDgOSefkgSyIJF/Mz0U6czow8Qo=</HostId>
</Error>
````

**Comment by tomhughes** [comment] 2024-08-14 08:27
I think those happened after I did an initial manual fix and before the root cause was dealt with. I've resynced it again now.
