### ISSUE TITLE
Tiles at openstreetmap.org are not accessible from Russia

### ISSUE THREAD

**Issue by dbf256** [openstreetmap/operations#378] opened 2020-03-21 08:44 UTC
Hi,
we have several users from Russia complain that tiles are not available at openstreetmap.org (it is possible to see top bar etc, but site tiles are missing).
In dev tools it looks this way:

![image](https://user-images.githubusercontent.com/2550295/77222914-cbe86f80-6b68-11ea-904e-df57f9cd60b8.png)

And when I try to ping these hosts it looks like a dns issue:

>ping c.tile.openstreetmap.org
Ping request could not find host c.tile.openstreetmap.org. Please check the name and try again.

There is no such problem when I connect using VPN with exit-node in Netherlands, for example.
Could you please check - is there any issue with tile dns balancer that could affect Russian users. 
I could expect that there is some issue with ISP etc, but it is reported by several users.

Let me know if you need any additional details or if it should be reported somewhere else.

Thanks.

**Comment by akuckartz** [comment] 2020-03-21 08:54
Are these two files really requested using http and not using http*s* ?

Which DNS servers are used ?

**Comment by tomhughes** [comment] 2020-03-21 09:18
There are no known problems at our end - this is far more likely to be some sort of routing issue or active blocking closer to the end users.

**Comment by tomhughes** [comment] 2020-03-21 09:21
If you want the list of servers then just ask the DNS what they are ;-)

```
% host -t ns geo.openstreetmap.org
geo.openstreetmap.org name server jakelong.openstreetmap.org.
geo.openstreetmap.org name server saphira.openstreetmap.org.
geo.openstreetmap.org name server katie.openstreetmap.org.
geo.openstreetmap.org name server stormfly-02.openstreetmap.org.
geo.openstreetmap.org name server chrysophylax.openstreetmap.org.
geo.openstreetmap.org name server ridgeback.openstreetmap.org.
```
If you can identify a server that's not reachable then we can check it out but as far as I know they are all working fine.

**Comment by zorun** [comment] 2020-03-21 09:29
There does seem to be an issue, the moscow tile server has no IP address associated to it:

```
$ dig +short c.tile.openstreetmap.org
tile.geo.openstreetmap.org.
moscow.tile.openstreetmap.org.
$ dig +short moscow.tile.openstreetmap.org.
$
```

**Comment by akuckartz** [comment] 2020-03-21 09:29
@dbf256 You perhaps use other DNS servers and therefore get a different list of servers for the *.tiles.openstreetmap.org domains than @tomhughes

**Comment by tomhughes** [comment] 2020-03-21 09:34
Hmm that's odd...

I've run a push and it seems to be fixed now - will need to investigate further and see if I can work out how that happened as it really shouldn't be possible.

**Closed by tomhughes** 2020-03-21 09:34 UTC

**Comment by zorun** [comment] 2020-03-21 09:44
Given that the redirection was working fine, it seems more a problem from cloudflare than from the geodns servers.

**Comment by petrpisaratlascz** [comment] 2020-03-21 09:59
I experience the same issue. My problem is that all the DNS servers where tile.openstreetmap.org. domain is delegated to refuse my queries on the DNS protocol level.

Here is the list of servers I get:

~~~~
$ dig  -t NS tile.openstreetmap.org. @rajeev.ns.cloudflare.com.

; <<>> DiG 9.14.8 <<>> -t NS tile.openstreetmap.org. @rajeev.ns.cloudflare.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47407
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 6, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;tile.openstreetmap.org.                IN      NS

;; ANSWER SECTION:
tile.openstreetmap.org. 86400   IN      CNAME   tile.geo.openstreetmap.org.

;; AUTHORITY SECTION:
geo.openstreetmap.org.  86400   IN      NS      saphira.openstreetmap.org.
geo.openstreetmap.org.  86400   IN      NS      ridgeback.openstreetmap.org.
geo.openstreetmap.org.  86400   IN      NS      jakelong.openstreetmap.org.
geo.openstreetmap.org.  86400   IN      NS      katie.openstreetmap.org.
geo.openstreetmap.org.  86400   IN      NS      stormfly-02.openstreetmap.org.
geo.openstreetmap.org.  86400   IN      NS      chrysophylax.openstreetmap.org.
~~~~

And whatever I use, to query an AAAA for a.tile.openstreetmap.org, I'm rejected:

$ dig -t AAAA a.tile.openstreetmap.org. @saphira.openstreetmap.org.

; <<>> DiG 9.14.8 <<>> -t AAAA a.tile.openstreetmap.org. @saphira.openstreetmap.org.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 10590
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1024
;; QUESTION SECTION:
;a.tile.openstreetmap.org.      IN      AAAA

;; Query time: 43 msec
;; SERVER: 2001:ba8:0:2c1e::#53(2001:ba8:0:2c1e::)
;; WHEN: So bře 21 10:53:52 CET 2020
;; MSG SIZE  rcvd: 53

The same happens over IPv4:

$ dig -4 -t A a.tile.openstreetmap.org. @saphira.openstreetmap.org.

; <<>> DiG 9.14.8 <<>> -4 -t A a.tile.openstreetmap.org. @saphira.openstreetmap.org.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: REFUSED, id: 50403
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1024
;; QUESTION SECTION:
;a.tile.openstreetmap.org.      IN      A

;; Query time: 43 msec
;; SERVER: 185.73.44.30#53(185.73.44.30)
;; WHEN: So bře 21 10:55:10 CET 2020
;; MSG SIZE  rcvd: 53
~~~~

And my IPv4 (CZ) and IPv6 (DE) locations differ. I can even reproduce it from a different autonomous system in the Czech Republic. I guess there something wrong with your authoritative DNS servers.

**Comment by tomhughes** [comment] 2020-03-21 10:11
You can't resolve `a.tile.openstreetmap.org` against that server - that server only serves `geo.openstreetmap.org` names. Here's the resolution chain:

```
% host a.tile.openstreetmap.org
a.tile.openstreetmap.org is an alias for tile.geo.openstreetmap.org.
tile.geo.openstreetmap.org is an alias for london-02.tile.openstreetmap.org.
london-02.tile.openstreetmap.org has address 185.73.44.167
london-02.tile.openstreetmap.org has IPv6 address 2001:ba8:0:2ca7::
```
Only the second result comes from the servers Iisted - the others are all from cloudflare.

**Comment by petrpisaratlascz** [comment] 2020-03-21 10:42
I see. My bad. The proper resolution chain for a.tile.openstreetmap.org works
for me again. But I bet it did not work few minutes ago. If I see the failure
again, I will try inspect it more carefully.

**Comment by tomhughes** [comment] 2020-03-21 10:47
Yes it was broken - the `moscow.tile.openstreetmap.org` record was missing from cloudflare as somebody pointed out and I fixed that.

**Comment by dbf256** [comment] 2020-03-21 12:09
Thanks, @tomhughes. There were several comments that tiles are fixed now.
