### ISSUE TITLE
Replace errol as dev server

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/operations#677] opened 2022-07-14 06:39 UTC
errol, the dev server, is 12 years old, and in need of replacement. Its replacement should have more CPU and use SSDs for maintenance and performance reasons.

As a server that has been running for over a decade, it, as might be expected, has a lot of old stuff on it. We want to figure out what is unmaintained and unused so we can remove it and get a better estimate of resources needed.

- [ ] Email people with accounts that they need to log-in within 3/6 months for us to retain their accounts

**Comment by grischard** [comment] 2022-07-29 16:31
Duplicate of #545, or at least mergeable with it?

**Closed** 2022-07-29 19:38 UTC

**Comment by Firefishy** [comment] 2022-07-29 20:49
I have emailed all users of the Dev server asking the following:
1) Please delete any of your files on the server which you no longer need.
2) Please let us know if you NO LONGER require your account and are
happy for us to delete your user-data on the dev server.
3) To keep your account active, please login over the next 2 weeks and
at least once every 3 months thereafter.

**Comment by Firefishy** [comment] 2022-09-26 13:58
Server is up, users being migrated in https://github.com/openstreetmap/operations/issues/752
