### ISSUE TITLE
Redirect irc.openstreetmap.org

### ISSUE THREAD

**Issue by systemed** [openstreetmap/operations#375] opened 2020-03-05 10:47 UTC
OFTC have asked that we no longer run irc.openstreetmap.org as it makes it harder for them to manage abuse.

They have their own web client at https://webchat.oftc.net . This can take a channel parameter (https://webchat.oftc.net?channels=osm) and can be used as an iframe (see menu top left).

I guess the most user-friendly thing to do, while keeping OFTC happy, would be to replace irc.openstreetmap.org with either a redirect to webchat.oftc.net or to put an iframe there.

**Comment by tomhughes** [comment] 2020-03-05 10:56
Duplicate of #374.

**Closed by tomhughes** 2020-03-05 10:56 UTC
