### ISSUE TITLE
Avoid rate-limiting genuine mapping activity

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/operations#36] opened 2015-06-22 09:11 UTC
We have a rate limiter applied to the API, which prevents people from scraping it when they should be using planet-dump resources instead. It is IP based and restricts the bytes-per-second of cgimap responses for a particular IP address.

Unfortunately this has caused problems for several mapping parties where large numbers (20+) mappers are behind the same IP address and mapping simultaneously.

There are a number of options available, including as IP whitelists or applying rates to specific logged-in users. The two aims are to a) prevent scraping of the API and b) not to prevent genuine mapping activity.

We need to discuss the various approaches here and decide what we want to try. The implementation of any changes will likely be tracked elsewhere (e.g. cgimap, openstreetmap-website, chef etc) and we may need to create some tools to measure the effectiveness of any changes.

**Comment by zerebubuth** [comment] 2015-06-22 09:37
IP whitelisting with the current (memcached) mechanism will not work reliably; memcached will drop keys occasionally, which is appropriate behaviour for a cache, and it's okay for current usage as it will randomly "forgive" a rate limit. However, if it were to drop a whitelist entry then it's likely to cause issues. Of course, we could whitelist IPs through the website instead -- i just wanted to point out that doing it as a quick hack on top of the existing rate limiter is likely to have unintended consequences.

IMHO, there are two other options which make a lot of sense:

1. Local caching proxies. It has long been on everyone's wish-list to have an "API in a box" to deploy at mapping parties, and there's no technical reason why it cannot be done. Between caching of map requests and diffs, it would be possible to provide better latency and experience for people at the mapping party (regardless of rate limits, bandwidth is often in short supply).
2. As @tomhughes said, rate limiting per-user rather than per-IP. This would require cgimap to understand OAuth requests, which it will need to anyway for upload support. The downside of this is that I do not think most editors routinely sign map requests, so they will (all) need a small change to do so.

**Comment by mapmeld** [comment] 2015-06-23 19:39
hi, I've been following this discussion in a few different places ever since I encountered this issue a few days ago at our mapping party at IT Park, Ulaanbaatar, Mongolia.

I am reluctant to endorse squid caching or "API in a box" type solutions, as this would be outside most organizers' experience. I've set up squid on an WiFi - internet gateway in Haiti before, and I just can't see installing my own system in place of a venue's existing IT infrastructure.

@zerebubuth mentioned on an e-mail that https://github.com/zerebubuth/cgimap-ruby could be used to start implementing per-user limits on cgimap. My understanding is that cgimap-ruby would be on top of cgimap, meaning that C++ cgimap would need an update to support user-specific limits. The main concern with this approach is that it takes a good amount of political and technical will to get it done.

Are there any useful intermediate steps? I was thinking that an API key would be easier to implement and test ahead of switching over to user authentication, but the API keys would need to be registered somewhere, and later retrieved from persistent storage (Postgres) if they weren't in memcached at the time.

**Comment by zerebubuth** [comment] 2015-06-23 20:09
@mapmeld Sorry, looks like I didn't do a good job of explaining what I meant by local caching / "API in a box": I wasn't thinking of a transparent cache or anything that would need to be installed in place of existing infrastructure. Ideally, it could be made as simple as a program that could be downloaded, run and displays a message saying

> API-in-a-box running, set your API URL in JOSM to http://192.168.0.5/api/0.6

Or something like that.

I've also managed to confuse the issue with cgimap-ruby: It's not required to start implementing per-user limits, that can be done with just cgimap. And I'm not sure I share your concern about needing political will -- perhaps you could expand on what concerns you?

As for next steps: The next missing piece for the per-user limits item is support for verifying OAuth (1.0a & 2) tokens in cgimap (which I'd be very happy to get a PR for!). Supporting 1.0a seems straightforward, but I had a great deal of trouble reading the RFC for OAuth2. Perhaps someone else would have better luck.

For the "API-in-a-box" item, it's something that is completely greenfield and independent of the API, so can be worked on in any order by anyone.

**Comment by tomhughes** [comment] 2015-06-23 20:11
No need for OAuth 2 - we only support 1.0 and 1.0a currently.

**Comment by gravitystorm** [comment] 2015-06-24 06:27
Lets not get too lost in the implementation details yet - have we decided how we want the rate-limiting to work? Is lifting the cap on logged in users adequate? Should there be the same cap, just per-user, or should there be a higher cap? Should the cap reset when a changeset is applied? Are the cap values reasonable given the increased data density, especially in well-mapped urban areas? Are there other approaches we want to consider?

It's best to decide how we want it to work before worrying about e.g. supported OAuth versions.

**Comment by Firefishy** [comment] 2015-06-24 07:15
In the interim, please can we double the current bucket top-up rate? We should have enough log data to work with already.

When the rate-limiting was introduced our infrastructure could not handle the extra load, it can now.

**Comment by tomhughes** [comment] 2015-06-24 07:28
@gravitystorm the point is that once we go to per-user limits we shouldn't need to increase the limit as each user will have their own instead of one being shared by everybody.

@Firefishy the bottleneck here is largely the database rather than the frontend machines, so it's not quite that clear, and in any case I see no reason to believe that doubling it will fix the problem - maybe it will, maybe it won't, we just have no idea.

**Comment by zerebubuth** [comment] 2015-06-24 07:46
> Is lifting the cap on logged in users adequate?

As @tomhughes says, the point isn't to lift the cap on logged-in users, it's two-fold; one is that each user is accounted separately, so that a normal level of usage won't get limited even when there are 100s of people behind a single NAT IP. The other is that we'll have the details of any account repeatedly hitting the limit so that we can suggest alternatives like Overpass to them, whereas currently we have no way of contacting people from just an IP address.

> Should there be the same cap, just per-user, or should there be a higher cap?
> Are the cap values reasonable given the increased data density, especially in well-mapped urban areas?

I don't think we'll be able to answer this question until we have per-user caps. Anecdotal evidence from mapping parties suggests that hitting the cap is not uncommon, but since there'll be a self-reporting bias in favour of those who get limited, it's hard to know the true numbers.

> Should the cap reset when a changeset is applied?

Personally, I don't think so. The issue with providing an "escape hatch" like this is that it's very easy to abuse by (e.g) uploading a changeset with a single untagged node in it.

> Are there other approaches we want to consider?

I believe the answer isn't really rate limiting. The reason we have rate limiting in the first place is to try to prevent the minuscule minority of extremely heavy users of the API from degrading the service for the majority of light users. When looked at like this, there are several possible solutions:

1. Adjusting the rate limiting scheme, as we're talking about here.
2. Moving to more of a delay-pools approach as we have for tiles where there is no "cap", the service just gets slower as your usage increases.
3. Increasing the capacity of the API servers (i.e: more read slaves).
4. Moving (some) read-only API calls off the core infrastructure. Either by local caching or CDN - some of which I talked about in my SOTM Birmingham talk.

While (4) is the _real_ fix, I think those items are roughly sorted from easiest to hardest.

**Comment by tomhughes** [comment] 2015-06-24 07:50
What we're doing is more or less exactly the same as delay-pools in that we rate limit people to a long term average of 100Kbyte/s.

The only difference is that delay pools slows down the sending while we actually deny some requests to keep the average down. That wouldn't work for us because it would tie up one of our limited number of server threads and more importantly the memory being used to hold the data - it works for tiles because that doesn't tie up server resource in the same way.

**Comment by zerebubuth** [comment] 2015-06-24 10:25
Assuming we did delay pools at the cgimap level. It's possible we could configure / install / write something to do delay pools at the Apache level, or even in front of it as an evented reverse proxy.

I was just thinking that perhaps people would be happier getting slow results rather than errors - it seems to work pretty well for the tile caches as a method for moderating excessive use.

**Comment by d3netxer** [comment] 2015-06-24 15:50
I also recommending having a custom page for the "509 Bandwidth Limit Exceeded" error, a page that contains a more detailed error message along with contact information on how to reach the operations team to temporarily lift the throttling cap.

**Comment by d3netxer** [comment] 2015-06-24 16:06
@zerebubuth you mentioned the downside of per-user limits on cgimap is needing editors to routinely sign map requests. What is signing map requests? Is this when a user needs an API key when downloading data from an API?

Maybe the signing-in requirement can be triggered once the bandwith threshold is exceeded?

**Comment by gravitystorm** [comment] 2015-06-24 16:22
> is needing editors to routinely sign map requests

This is a technical statement, regarding editing software (e.g. iD, JOSM) and OAuth signing of requests. The mappers would not be directly affected or know what's going on.

**Comment by zerebubuth** [comment] 2015-06-24 16:30
@d3nexter what I meant by "signed map requests" is that the OAuth system which we use authenticates users based on a cryptographic signature of the request. See [oauth.net](http://oauth.net/) for the details. Since we already require authentication for any request uploading data to the API, any necessary code will already be implemented in all OSM editing clients, and all clients will have the necessary tokens to perform operations. Therefore, it should be a small change to authenticate all map requests as well, or a slightly larger change for editor clients to switch to authenticated requests after getting the first 509 and retry.

We do display some information for the 509 ("You have downloaded too much data. Please try again later."), but making that more informative is a good idea. Ultimately, though, contacting the operations team isn't a good way of dealing with this issue as it relies on us being available and capable of dealing with the volume of requests. It's not "scalable", in other words.

Having said that, I think there's an alternative we've not yet considered, perhaps we've focussed too much on the API... But we could recommend that editors switch to another source (e.g: Overpass) when they get a 509, at least temporarily. This would sort of fix the problem, with the only drawback that Overpass might be a minute behind the API. But most editing sessions will be of comparable or longer length.

**Comment by pnorman** [comment] 2015-06-24 17:15
> Are the cap values reasonable given the increased data density, especially in well-mapped urban areas?

I'm skeptical on this - I've hit the cap with the data viewer through the website. But I don't have any real data on what would be appropriate.

> This would sort of fix the problem, with the only drawback that Overpass might be a minute behind the API. But most editing sessions will be of comparable or longer length.

iD doesn't process the diff from the server, so using any replication diff based service will result in features disappearing from the local view on save (openstreetmap/iD#2678).

I wonder how much extra traffic openstreetmap/iD#1646 is generating. Every time an iD user saves, their local view of OSM is thrown away and they have to re-download from the API.

**Comment by d3netxer** [comment] 2015-06-30 20:23
It seems to me that applying rates to specific logged-in users instead of IPs is the best long-term solution.

**Comment by pnorman** [comment] 2016-08-27 08:01
Does zerebubuth/openstreetmap-cgimap#110 take care of the server-side changes? Is the next step to get editors to sign requests?

**Comment by tomhughes** [comment] 2016-08-27 09:06
I don't think that PR is live yet. I think @zerebubuth was going to build a copy of cgimap into the admins PPA and then we were going to switch to that instead of building from source?

**Comment by zerebubuth** [comment] 2016-08-27 16:34
Yup, that version isn't live yet. And the plan as @tomhughes describes is correct. I was hoping to land the changesets PR (zerebubuth/openstreetmap-cgimap#111) as well, but I still don't feel massively confident about it.

Another approach would be to have a cgimap-next.dev.openstreetmap.org which would be cgimap pointing at api06's database (perhaps also forwarding non-handled calls to api06's rails), so we could test editors against it before it goes live. Does that sound worth doing, or do we not need to be that cautious?

**Comment by tomhughes** [comment] 2016-08-27 18:30
Well no current editor will authenticate map calls so I say we just go for it and people can then test editors against it anyay?

Only risk would be if it broke unauthenticated downloads an we can catch that quickly enough if we just roll it out to one machine first and watch the logs for a few minutes to make sure it's ok. Certainly less work than getting a dev instance up which we're not setup for at all at the moment.

**Comment by pnorman** [comment] 2016-08-27 22:20
> Another approach would be to have a cgimap-next.dev.openstreetmap.org which would be cgimap pointing at api06's database (perhaps also forwarding non-handled calls to api06's rails), so we could test editors against it before it goes live. Does that sound worth doing, or do we not need to be that cautious?

I think it's worth doing so it better reflects production, but not required for this PR. I'm with tom for how to deploy it.

**Comment by zerebubuth** [comment] 2016-10-17 16:57
Just a note that this was deployed on Wednesday 2016-10-12. I'm looking forward to seeing support in editors! If anyone would like help with that, please get in touch.

This issue is about avoiding the limits and, although the mechanism for that is now deployed, I think we should leave it open until support is available in at least iD and JOSM to check that the effect is as desired. That is; people at mapping parties who are logged in don't get rate-limited.

**Comment by don-vip** [comment] 2016-10-30 14:53
JOSM support is enabled in 11193+, see https://josm.openstreetmap.de/ticket/13872

**Comment by zerebubuth** [comment] 2016-10-31 09:48
Many thanks to @bhousel and @don-vip for adding support into iD and JOSM. You've made editing OSM much easier for people at mapping parties! :smile: 

I'm closing this ticket, as I think we've done what we can for the moment. I intend to follow up with some mapping party organisers to see if the problem is solved or we need to take further steps (in new issues).

**Closed by zerebubuth** 2016-10-31 09:48 UTC
