### ISSUE TITLE
Weekly planet PBF not released for last 3 weeks

### ISSUE THREAD

**Issue by rouen-sk** [openstreetmap/operations#570] opened 2021-09-30 07:52 UTC
Last planet file available is `planet-210906.osm.pbf`, by now there should be `210913`, `210920` and `210927`. Lot of people and organizations are not running replication and rely on planet dumps for some periodic processing. I did not find any statement about this issue. Any idea when the planet releases will be resumed? Thanks.

**Comment by tomhughes** [comment] 2021-09-30 07:54
Duplicate of #568.

**Closed by tomhughes** 2021-09-30 07:54 UTC

**Comment by rouen-sk** [comment] 2021-09-30 08:27
> Any idea when the planet releases will be resumed?

**Comment by tomhughes** [comment] 2021-09-30 08:35
There's nothing to resume - they are continuing on their normal schedule and assuming nothing goes wrong this week it will appear when it is finished probably sometime on Saturday.
