### ISSUE TITLE
Favicon for forum

### ISSUE THREAD

**Issue by TZornG** [openstreetmap/operations#314] opened 2019-07-16 08:50 UTC
Could you please add a favicon to the forum website?

**Comment by Tigerfell** [comment] 2019-07-20 10:40
I guess this relates to #248 where I just made a suggestion for a potential logo.

**Comment by Tigerfell** [comment] 2019-07-26 10:51
Duplicate of OSM-Forum/openstreetmap-forum#10

**Comment by mmd-osm** [comment] 2019-11-12 22:17
@TZornG : can you close this issue and follow up in #248? Thanks.

**Comment by TZornG** [comment] 2019-11-13 18:20
Followed up in #248 .

**Closed** 2019-11-13 18:20 UTC
