### ISSUE TITLE
Unable to renew my OSM Foundation membership (“Payment Processor Error message :DB Error: unknown error”)

### ISSUE THREAD

**Issue by amandasaurus** [openstreetmap/operations#973] opened 2023-10-09 06:40 UTC
The autorenew of my OSMF membership didn't work (probably because I got a new credit card a few months ago after being pickpocketed). So I clicked on the link, and tried to fill in the form, and got: “Payment Processor Error message :DB Error: unknown error”

![image](https://github.com/openstreetmap/operations/assets/1547/d5f2cd4b-1f35-41cb-893a-f4a19f7eeeca)

I tried to sign up new at <https://supporting.openstreetmap.org/normal-membership/> and got the same error:

![image](https://github.com/openstreetmap/operations/assets/1547/7055dceb-e922-441a-84ea-fbd667819939)

I posted this on the `#osmf-membership` IRC channel on 2023-10-07, and emailed MWG on 2023-10-09, and also chatted to @Firefishy on IRC that day. He thinks #972 might be relevant too.

**Comment by amandasaurus** [comment] 2023-10-09 13:34
On Mon, 09 Oct 2023 14:59 +02:00, Grant ***@***.***> wrote:
> Have you retried since then?

Yes I did that this morning, and took those screenshots this morning

-- 
Amanda

**Comment by Firefishy** [comment] 2023-10-09 14:11
@grischard Assigning this one to you. Let me know if you'd like me to investigate.

**Comment by amandasaurus** [comment] 2023-10-10 07:23
It's basically homophobia. 😜

I changed my OSM username and got it to work. Through trial and error, I could reproduce the error when I had a 🏳️‍🌈 character at the end of my username. The [Ogham](https://en.wikipedia.org/wiki/Ogham) letters (`…ᚐᚋᚐᚅᚇᚐ…`) are not a problem.

I was able to crash the civicrm OSMF membership system by changing my OSM username. That's not good.

**Comment by Firefishy** [comment] 2023-10-10 13:28
Likely a mysql utf8 issue then. 🏳️‍🌈 flag is 4 characters and 14 bytes. By default mysql utf8 is only supports I believe 4 character. Needs further investigation.

**Comment by Firefishy** [comment] 2023-10-10 13:40
Confirmed civicrm uses `utf8mb3_unicode_ci` and not the `mb4` version, looks like there may be [a process to convert to mb4](https://civicrm.stackexchange.com/a/37939). @grischard

**Comment by tomhughes** [comment] 2023-10-10 13:52
> It's basically homophobia. 😜 [/s](https://en.wikipedia.org/wiki/Tone_indicator)

I don't care if you added a smiley - that comment is totally inappropriate.

That comment is the first indication that the problem has anything to do with your username and without giving anybody a chance to address what is fairly obviously a bug you essentially imply that is a deliberate act of discrimination.

**Comment by grischard** [comment] 2023-10-10 14:06
> Confirmed our civicrm uses `utf8mb3_unicode_ci` and not the `mb4` version, looks like there may be [a process to convert to mb4](https://civicrm.stackexchange.com/a/37939). @grischard

Running the upgrade process.

**Comment by amandasaurus** [comment] 2023-10-10 14:32
On Tue, 10 Oct 2023 15:52 +02:00, Tom Hughes ***@***.***> wrote:
>> It's basically homophobia. 😜 /s <https://en.wikipedia.org/wiki/Tone_indicator>
>> 
> I don't care if you added a smiley - that comment is totally inappropriate.

My apologies. It was an attempt to being light hearted and joking.

-- 
Amanda

**Comment by grischard** [comment] 2023-10-10 15:28
MySQL upgrade done.

**Comment by Firefishy** [comment] 2023-10-11 13:49
I am going to close this now. If the issue remains we can re-open.

**Closed by Firefishy** 2023-10-11 13:49 UTC
Labels: wordpress, foundation
