### ISSUE TITLE
Missing thumbnails with large image galleries in the wiki

### ISSUE THREAD

**Issue by duiveldoder** [openstreetmap/operations#573] opened 2021-10-26 17:19 UTC
Dear Sir, Madam,

I talked a lot in the Telegram groups about this issue to make sure it's not just me. But a lot of people report the wiki.openstreetmap.org is loading extremely slow and as I discovered not only so slow that it's annoying it's even generating bugs because of the poor performance of the server.

https://en.wikipedia.org/wiki/Road_signs_in_the_Philippines has no problem rendering the thumbnails within a second and showing it to the user.

Porting it to wiki.openstreetmap.org and changing it into an easy lookup table for the mapper plus adding the official government ID to each sign, there are many issues
1) loading takes ages sometimes
2) half of the thumbnails aren't loaded

A possible reason why wiki.openstreetmap.org is creating errors - opposed to wikipedia.org which doesn't have any problems - I found an entry at dreamhost guide, source:  https://help.dreamhost.com/hc/en-us/articles/217292577-MediaWiki-Installing-and-more

**MediaWiki can occasionally have problems generating image thumbnails, such as returning corrupted images or the error message "Error creating thumbnail". A common cause of this is not enough memory.**

**If you upload a large image and see "Error creating thumbnail" where a thumbnail should be, try adding the following to your LocalSettings.php file in your site’s primary directory:**

**$wgMaxShellMemory = 524288;**

Maybe this won't solve the issue at hand - who knows - but I'm quite sure it's a server performance issue.

When looking at the "page source" what the server returns..

up to the point it loads the embedded thumbnails properly I see:

```
</p>
			</div>
		</div></li>
		<li class="gallerybox" style="width: 45px"><div style="width: 45px">
			<div class="thumb" style="width: 40px;"><div style="margin:0px auto;"><a href="/wiki/File:Philippines_road_sign_R2-3_R.svg" class="image"><img alt="" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Philippines_road_sign_R2-3_R.svg/40px-Philippines_road_sign_R2-3_R.svg.png" decoding="async" width="40" height="40" srcset="https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Philippines_road_sign_R2-3_R.svg/60px-Philippines_road_sign_R2-3_R.svg.png 1.5x, https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Philippines_road_sign_R2-3_R.svg/80px-Philippines_road_sign_R2-3_R.svg.png 2x" /></a></div></div>
			<div class="gallerytext">
<p><b>R2-3 (R)</b>
```

But from the moment the error arises it doesn't return to the user inside the generated html the links:

```
</p>
			</div>
		</div></li>
		<li class="gallerybox" style="width: 45px"><div style="width: 45px">
			<div class="thumb" style="height: 40px;"></div>
			<div class="gallerytext">
<p><b>W8-9</b>
```

See it's empty!

**Comment by duiveldoder** [comment] 2021-10-29 20:52
Sad, the issue came back now

it worked well for 24+ hours

but now (evening time Europe 29 October 2021) it came back

**Comment by duiveldoder** [comment] 2021-10-31 12:16
Hi Tom, the "File:" can be omitted within a gallery..

Says the manual of the MediaWiki

I saw you put back the "File:"

it doesn't make a difference - tried that already

**Comment by duiveldoder** [comment] 2021-12-23 04:41
Hello Tom,

https://www.mediawiki.org/wiki/Extension:QuickInstantCommons

Might this be something to try to resolve this issue?

**Comment by happy5214** [comment] 2022-03-28 01:15
> Hello Tom,
> 
> https://www.mediawiki.org/wiki/Extension:QuickInstantCommons
> 
> Might this be something to try to resolve this issue?

QuickInstantCommons is now listed as stable on the MediaWiki project wiki (it was in beta as of the above comment). Perhaps this should be further investigated?

**Comment by matkoniecz** [comment] 2022-04-05 07:11
It was investigated and turned out to be not stable - see https://github.com/openstreetmap/chef/pull/491 and https://github.com/wikimedia/mediawiki-extensions-QuickInstantCommons/issues/1

**Comment by duiveldoder** [comment] 2022-04-10 23:24
> It was investigated and turned out to be not stable - see [openstreetmap/chef#491](https://github.com/openstreetmap/chef/pull/491) and [wikimedia/mediawiki-extensions-QuickInstantCommons#1](https://github.com/wikimedia/mediawiki-extensions-QuickInstantCommons/issues/1)

Yes I read a few other comments elsewhere from other wiki page admins stating it's not yet stable.. there's still some work to do.

I totally agree stability first! At my home private server stability isn't much of an issue - usually I can deal with it.

But a public available space you make the right call to go for stability first. IMHO

**Comment by tomhughes** [comment] 2022-04-12 15:57
Closing as duplicate of #466.

**Closed by tomhughes** 2022-04-12 15:57 UTC
Labels: service:wiki

**Comment by Firefishy** [comment] 2022-08-04 00:42
I have now enabled [QuickInstantCommons](https://www.mediawiki.org/wiki/Extension:QuickInstantCommons) but I am not 100% happy as we are using the `master` branch instead of a [REL1_37](https://github.com/wikimedia/mediawiki-extensions-QuickInstantCommons/issues/2) branch.

**Comment by duiveldoder** [comment] 2022-12-22 01:11
I tested this extensively over a few months - because I hate to report something has been fixed - or not, without doing a long-term observation if it's really the case what I'm saying.

So now I can say with 100% confidence:"all problems I had have been resolved in this matter"

Thank you very much to the team taking care of us mappers :)
