### ISSUE TITLE
Consider TZ offset for daily cron jobs

### ISSUE THREAD

**Issue by jburgess777** [openstreetmap/operations#234] opened 2018-08-08 00:31 UTC
Our default daily cron jobs such as rotating the log files on the tile caches some time after 6AM UTC regardless of where the machine is located. This is a relatively idle time for some machines, but for others like Longma this is during a period of high load. I think we should consider the TZ offset in the /etc/crontab rules to move the daily jobs to a better time of day. 

Gorynych is another machine which suffers from this.

**Comment by tomhughes** [comment] 2018-08-08 06:07
It's a nice idea but I'm not sure how it would actually be achieved - the best I can come up with is to remove the `cron.daily` entry (but updates to logrotate would put it back) and add a separate timed cron entry to run logrotate.

**Comment by tomhughes** [comment] 2018-08-08 08:04
So there is a way - if you set TZ in the environment of crond then it will affect when jobs run but won't propagate to the environment seen by the jobs themselves.

So the question is, should we try and configure all machines to run cron jobs in the machines real time zone?

**Comment by Firefishy** [comment] 2018-08-08 08:10
Yes, setting a local crond TZ environment variable for local time sounds reasonable to me, unless the configuration required is crazy.

**Comment by zorun** [comment] 2019-07-26 09:28
This issue could explain part of the high response time on some caches.  Well, of course the root cause is too much load in general.

logrotate runs around 6.30 AM UTC and takes an absurd amount of time (up to around 2 hours), because it compresses ~10 of GB of squid log using xz.

The impact on response time is sometimes visible when load picks up during this logrotate job:

- kiezer: #299
- necrosan: [response time](https://munin.openstreetmap.org/openstreetmap.org/necrosan.openstreetmap.org/squid_times.html) and [CPU load](https://munin.openstreetmap.org/openstreetmap.org/necrosan.openstreetmap.org/cpu.html)

It would be a good idea to shift this cron job to a local idle hour, or keep less logs, or use a faster compression algorithm.

**Comment by tomhughes** [comment] 2019-07-28 09:05
I think there are actually two issues - the first is that the servers are all running in local time so daily jobs intended to run in the middle of the night may not actually do so.

The second is that Ubuntu for some reason runs `cron.daily` etc surprisingly late - it starts `cron.daily` at 06:25 for example while Fedora starts it at 03:00 which seems much more reasonable.

The combination means that even machines in europe can be pushed to say 08:25 in summer when load is likely to be picking up.

**Comment by pnorman** [comment] 2022-07-08 05:51
This was an issue when we had tile caches all around the world with high volume logs, and a relationship between the server's time zone and usage. This is not really the case anymore, with the high volume of tile request logs being handled by Fastly and compressed every 10 minutes.

Is there still anything to be done here?

**Comment by tomhughes** [comment] 2022-07-08 16:55
It was actually mostly implemented in https://github.com/tomhughes/openstreetmap-chef/commit/541ddf990024bb235eb44265f584125dd641063f anyway though that doesn't work for things which have since been converted to run as systemd timers instead of cron jobs.

**Comment by tomhughes** [comment] 2022-07-08 16:56
There was some reason why I left this open - some additional work I had in mind - but I can't remember what it was.

**Comment by pnorman** [comment] 2022-11-18 21:47
Do we know what the work to be done is, or can we close this?

**Comment by tomhughes** [comment] 2022-11-18 22:41
This was mostly an issue for the tile caches which are obviously no longer an issue.

Our general intention is to move cron jobs to systemd timers and with those you have the option of running in local system time (which is always UTC for us) or a named timezone so we the infrastructure we added to chef to be able to use local geographic time in cron would provide the timezone we needed for a systemd timer if we wanted one to run that way.

So I think we can probably close this.

**Closed by tomhughes** 2022-11-18 22:41 UTC
