### ISSUE TITLE
Special:ItemByTitle reports error if data item doesn't exist since update to MediaWiki 1.39

### ISSUE THREAD

**Issue by chram2** [openstreetmap/operations#858] opened 2023-03-11 18:45 UTC
Hi! Since last Wiki update to MediaWiki 1.39 there is an error with using "Special:ItemByTitle" https://wiki.openstreetmap.org/wiki/Special:ItemByTitle/wiki/ if a data item does not exist:

`[0cebc12a9f2b493b81298c39] 2023-03-11 18:30:53: Fatal exception of type "Error"`

You can try it here: https://wiki.openstreetmap.org/wiki/Special:ItemByTitle/wiki/?site=wiki&page=Key%3Awindings%3Aauto

This function is helpful and useful to create new data item as it looks for existing ones, and if no, provides a link to create the data item with site link set automatically.

Could someone from the operations team please take a look at this error and hopefully fix it?
Regards, Chris (Wiki user [Chris2map](https://wiki.openstreetmap.org/wiki/User:Chris2map))

**Comment by Firefishy** [comment] 2023-03-11 18:50
Likely needs to be someone from outside the Ops team who needs to work out what the issue is. The ops team are not mediawiki experts and less so for wikibase.

**Comment by Firefishy** [comment] 2023-03-11 18:50
Linked issue: https://github.com/openstreetmap/operations/issues/764

**Comment by Firefishy** [comment] 2023-03-11 18:51
@nyurik any chance you could advise?

**Comment by nyurik** [comment] 2023-03-11 19:04
will look at it tonight, thx for the ping

**Comment by chram2** [comment] 2023-03-11 19:08
@ Firefishy and nyurik - Thank you for quick response!
I had contacted wiki admin Tigerfell and he could not determine a cause within his reach on the wiki.
https://wiki.openstreetmap.org/wiki/Wiki:Requests_for_administrator_attention/Archive_1#Error_message_when_searching_for_a_data_item_by_Special:ItemByTitle

**Comment by nyurik** [comment] 2023-03-11 22:39
@Firefishy could you take a look at the logs - do you see the full stack trace for this error?  It's a bit difficult to debug without access :(

**Comment by tomhughes** [comment] 2023-03-11 23:57
I can't find any logs with anything useful in them. I don't think MW normally logs anything for errors does it, unless you enable the debugging mode where it sends them to the browser?

**Comment by GreenReaper** [comment] 2023-03-13 04:58
Try [$wgDebugLogFile](https://mediawiki.org/wiki/Manual:$wgDebugLogFile)? For displaying visibly you may be thinking of [$wgShowExceptionDetails](https://mediawiki.org/wiki/Manual:$wgShowExceptionDetails) or [other debugging variables](https://mediawiki.org/wiki/Category:Debug_variables).

**Comment by tomhughes** [comment] 2023-03-13 08:30
This is the exception I think:

```
[exception] [4abe62ec391a203643e2dd75] /wiki/Special:ItemByTitle/wiki/?site=wiki&page=Key%3Awindings%3Aauto   Error: Class "OsmWikibase\MediaWikiPageNameNormalizer" not found
#0 /srv/wiki.openstreetmap.org/w/extensions/Wikibase/repo/includes/Specials/SpecialItemByTitle.php(159): OsmWikibase\OsmSite->normalizePageName()
#1 /srv/wiki.openstreetmap.org/w/includes/specialpage/SpecialPage.php(701): Wikibase\Repo\Specials\SpecialItemByTitle->execute()
#2 /srv/wiki.openstreetmap.org/w/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
#3 /srv/wiki.openstreetmap.org/w/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#4 /srv/wiki.openstreetmap.org/w/includes/MediaWiki.php(904): MediaWiki->performRequest()
#5 /srv/wiki.openstreetmap.org/w/includes/MediaWiki.php(562): MediaWiki->main()
#6 /srv/wiki.openstreetmap.org/w/index.php(50): MediaWiki->run()
#7 /srv/wiki.openstreetmap.org/w/index.php(46): wfIndexMain()
#8 {main}
```

**Comment by tomhughes** [comment] 2023-03-13 08:32
So it looks like it's actually in https://github.com/nyurik/OsmWikibase rather that Wikibase itself... One for @nyurik I guess.

**Comment by nyurik** [comment] 2023-03-13 17:32
Thanks @tomhughes !  Will revisit this tonight.  We really ought to have a proper docker-based MW instance for all upgrade testing...  Esp because I think the wikibase community has done most of this work already, and its just for us to reuse their dockerfile work to add our own customizations.

**Comment by GreenReaper** [comment] 2023-03-13 18:12
Probably a good idea, although as of now [WMDE are still working on getting a Wikibase Suite 1.39 release out](https://phabricator.wikimedia.org/T329236).

**Comment by tacsipacsi** [comment] 2023-03-19 23:05
> This is the exception I think:
> 
> ```
> [exception] [4abe62ec391a203643e2dd75] /wiki/Special:ItemByTitle/wiki/?site=wiki&page=Key%3Awindings%3Aauto   Error: Class "OsmWikibase\MediaWikiPageNameNormalizer" not found
> #0 /srv/wiki.openstreetmap.org/w/extensions/Wikibase/repo/includes/Specials/SpecialItemByTitle.php(159): OsmWikibase\OsmSite->normalizePageName()
> #1 /srv/wiki.openstreetmap.org/w/includes/specialpage/SpecialPage.php(701): Wikibase\Repo\Specials\SpecialItemByTitle->execute()
> #2 /srv/wiki.openstreetmap.org/w/includes/specialpage/SpecialPageFactory.php(1428): SpecialPage->run()
> #3 /srv/wiki.openstreetmap.org/w/includes/MediaWiki.php(316): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
> #4 /srv/wiki.openstreetmap.org/w/includes/MediaWiki.php(904): MediaWiki->performRequest()
> #5 /srv/wiki.openstreetmap.org/w/includes/MediaWiki.php(562): MediaWiki->main()
> #6 /srv/wiki.openstreetmap.org/w/index.php(50): MediaWiki->run()
> #7 /srv/wiki.openstreetmap.org/w/index.php(46): wfIndexMain()
> #8 {main}
> ```

This should be fixed by nyurik/OsmWikibase#3. Hopefully the fix won’t just surface other errors…

**Comment by chram2** [comment] 2023-05-18 08:18
As the error continues to pop up for me, I wanted to ask if there is any progress?

**Comment by tomhughes** [comment] 2023-05-18 08:41
We continue to await a released fix from upstream.

**Comment by GreenReaper** [comment] 2023-05-18 08:54
By upstream you mean nyurik/OsmWikibase? I think it just needs that pull request applied; it's using a constant defined in the undeclared MediaWiki class.

**Comment by nyurik** [comment] 2023-05-22 08:18
i think this is fixed, major thanks to @tacsipacsi for the PR!

**Comment by tomhughes** [comment] 2023-05-22 08:23
I can confirm that fix has deployed to our production server.

**Closed by tomhughes** 2023-05-22 08:23 UTC
Labels: service:wiki, help-wanted
