### ISSUE TITLE
Tiles are not loading in zoom level 16 around 41.7968/-88.2333

### ISSUE THREAD

**Issue by baslr** [openstreetmap/operations#289] opened 2019-03-12 12:42 UTC
go to:
https://www.openstreetmap.org/#map=16/41.7968/-88.2333

headers:
```
Host: c.tile.openstreetmap.org
User-Agent: ***
Accept: image/webp,*/*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://www.openstreetmap.org/
DNT: 1
Connection: keep-alive
Cookie: _osm_totp_token=793053; qos_token=224583
TE: Trailers

HTTP/2.0 404 Not Found
server: nginx
date: Tue, 12 Mar 2019 12:41:56 GMT
content-type: text/html; charset=iso-8859-1
content-length: 313
expect-ct: max-age=0, report-uri="https://openstreetmap.report-uri.com/r/d/ct/reportOnly"
x-cache: MISS from trogdor.openstreetmap.org
x-cache-lookup: HIT from trogdor.openstreetmap.org:3128
via: 1.1 trogdor.openstreetmap.org:3128 (squid/2.7.STABLE9)
strict-transport-security: max-age=31536000; includeSubDomains; preload
X-Firefox-Spdy: h2
```

**Comment by tomhughes** [comment] 2019-03-12 12:47
Yes this happens sometimes for high zoom tiles when the servers are busy - we're working on it.

Duplicate of #281.

**Closed by tomhughes** 2019-03-12 12:47 UTC
