### ISSUE TITLE
More frequent "This website is under heavy load (queue full)"

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/operations#276] opened 2019-02-13 20:00 UTC
Recently I am quite often getting during editing.

> <h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>

>    Server returned status code 503

I suspect that it may be covered by #260 (though "queue full" suggests rather CPU/memory limitations) or some other already reported issue.

It is possible that I am just less lucky than in past.

Is it possible to reduce priority of software that is not critical for editing OSM? For example I think that it would be preferable to have Nominatim outages rather than editing API outages.

**Comment by tomhughes** [comment] 2019-02-13 20:37
We are already aware and are attempting to determine the underling cause.

**Comment by pnorman** [comment] 2019-02-13 22:08
> Is it possible to reduce priority of software that is not critical for editing OSM? For example I think that it would be preferable to have Nominatim outages rather than editing API outages.

They run completely independently.

**Comment by tomhughes** [comment] 2019-02-13 22:24
It's not a real resource issue anyway, rather that something had hung, probably because of a hardware issue.

**Comment by mmd-osm** [comment] 2019-02-14 17:58
It's odd that the same 100% CPU busy situation now also occurred on spike-02 and spike-03. I have never seen this before. Could this be some recent regression in the code somehow?

https://munin.openstreetmap.org/openstreetmap.org/spike-02.openstreetmap.org/cpu.html
https://munin.openstreetmap.org/openstreetmap.org/spike-03.openstreetmap.org/cpu.html

**Comment by tomhughes** [comment] 2019-02-14 22:39
This has been resolved by https://github.com/openstreetmap/openstreetmap-website/commit/89d387e66a50a32edb5e8eef2a9ef34565a90131and https://github.com/vmg/rinku/issues/84 has been opened upstream.

**Closed by tomhughes** 2019-02-14 22:39 UTC
