### ISSUE TITLE
Connection to Discourse unreliable since yesterday

### ISSUE THREAD

**Issue by malteger** [openstreetmap/operations#831] opened 2023-01-19 19:27 UTC
Since Yesterday (2023-10-18) I experience some problems using community.openstreetmap.org . The site usually works fine up to a certain point and fails to update counters and read states after that. If I try to reload it the browser immediately responds with 'Unable to connect'. I have observed that from two different internet connections on different times, the server status on https://uptime.openstreetmap.org/ is also jumping between up and down. It does not last very long, but is noticeable.

The graphs in https://prometheus.openstreetmap.org/d/Ea3IUVtMz/host-overview?orgId=1&var-instance=jakelong&from=1673987262457&to=1674152114246 do also show some unusual behaviour since 2023-10-18 20:30 UTC (which corresponds to a [commit to the chef repo](https://github.com/openstreetmap/chef/commit/5250ae5ea1263e0ea8ef4642cf63bd808ef0c0e6), but I fail to see how this could have the observed effect from the outside)

**Comment by tomhughes** [comment] 2023-01-19 19:31
The timing is coincidental - when I deployed that commit discourse also updated to a new version which is probably the real cause of the problems.

**Comment by Kovoschiz** [comment] 2023-01-21 05:27
Still "unable to connect" from time to time including now. Got an HTTP 502 last time.

**Comment by mmd-osm** [comment] 2023-01-21 13:24
Is this an upstream issue with Discourse?  Are they already aware that their latest update may be a bit broken?

**Comment by tomhughes** [comment] 2023-01-21 14:41
Well it was caused by a change that upstream made to their scripts which meant they were fighting with chef and constantly restarting the site - hopefully https://github.com/openstreetmap/chef/commit/5f6c31a1fa2ffa34a8d2ce071d8e539f74282817 has fixed it.

**Comment by mmd-osm** [comment] 2023-01-24 17:47
Uptime is 3 days 5 hours now. let’s close this one, as the issue has been resolved.

**Closed** 2023-01-24 17:51 UTC
Labels: service:discourse
