### ISSUE TITLE
sotm2020 website doesn't update itself anymore

### ISSUE THREAD

**Issue by tyrasd** [openstreetmap/operations#415] opened 2020-05-15 12:26 UTC
Latest changes from the https://github.com/openstreetmap/stateofthemap-2020 repository are not deployed on https://2020.stateofthemap.org anymore.

Not sure what could have caused this. From what I can see, the changes since the last update of the website are purely content related: https://github.com/openstreetmap/stateofthemap-2020/compare/60a02013a21e016d8827fd670a98d09e8d360375...master

//cc @ChristineKarch

**Comment by tomhughes** [comment] 2020-05-15 12:34
Sorry, it was caused by me doing a manual build after the previous breakage as the wrong user.

It should be fixed now.

**Closed by tomhughes** 2020-05-15 12:34 UTC
