### ISSUE TITLE
api.openstreetmap.org/api returning internal server error messages

### ISSUE THREAD

**Issue by donalhunt** [openstreetmap/operations#480] opened 2020-12-14 11:52 UTC
Attempting to upload changes in JOSM results in the following message:

`The OSM server 'https://api.openstreetmap.org/api/0.6/' reported an internal server error. This is most likely a temporary problem. Please try again later.`

Other users on telegram are reporting the same problem. I also attempted to test my oauth access token but that returns a similar message.

**Comment by tomhughes** [comment] 2020-12-14 12:17
I can see that there was a brief spike in errors but it looks like it is recovering now.

**Comment by mmd-osm** [comment] 2020-12-14 12:19
Still getting HTTP 500 for GET https://www.openstreetmap.org/api/0.6/user/details over here

**Comment by mmd-osm** [comment] 2020-12-14 12:26
Looks better now. Wondering what triggered this?

![image](https://user-images.githubusercontent.com/5842757/102081058-dee65280-3e0f-11eb-8e90-b79a50102f49.png)

**Comment by tomhughes** [comment] 2020-12-14 12:26
Yes I believe it should be fixed now.

**Closed by tomhughes** 2020-12-14 12:26 UTC

**Comment by gravitystorm** [comment] 2020-12-14 13:25
> Yes I believe it should be fixed now.

Can you let us know (briefly) what the problem was?

**Comment by tomhughes** [comment] 2020-12-14 13:29
A permanent fix will be provided later when I'm not doing my day job.

**Comment by tomhughes** [comment] 2020-12-14 14:56
So the root cause of the problem was that the `oauth_nonces` table used integer IDs and we had hit 2**32 so no more rows could be inserted.

I manually altered the table to use bigint IDs this morning to fix it and have now pushed https://github.com/openstreetmap/openstreetmap-website/commit/384ac4610262157e13f5a3d2656ac5023f35beea to reflect that change.
