### ISSUE TITLE
Minutely replication file missing 006/217/368.osc.gz

### ISSUE THREAD

**Issue by flohoff** [openstreetmap/operations#1146] opened 2024-08-14 08:24 UTC
Hi,
the file 006/217/368.osc.gz seems to be missing/failed to write - All the replication pipelines got stuck: 

This is /usr/bin/pyosmium-up-to-date output:

```
2024-08-14 06:22:22 DEBUG: https://planet.osm.org:443 "GET /replication/minute//006/217/368.osc.gz HTTP/1.1" 302 381
2024-08-14 06:22:22 DEBUG: https://osm-planet-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com:443 "GET /planet/replication/minute/006/217/368.osc.gz HTTP/1.1" 404 None
```

Thanks

Flo

**Comment by tomhughes** [comment] 2024-08-14 08:26
Duplicate of #1143, #1144 and #1145.

**Closed by tomhughes** 2024-08-14 08:26 UTC
