### ISSUE TITLE
api/changeset/*/upload returns Bad Request (400) - Bad OAuth request

### ISSUE THREAD

**Issue by westnordost** [openstreetmap/operations#481] opened 2020-12-14 12:16 UTC
Since 12:22 UTC+1, I get a lot of reports from StreetComplete users that the upload fails with the mentioned HTTP error code. Nothing changed on StreetComplete side.

**Comment by tomhughes** [comment] 2020-12-14 12:16
Duplicate of #480.

**Closed by tomhughes** 2020-12-14 12:16 UTC
